function [] = plotBeampatternPolar(thetaScanningAngles, beamPattern, dynRange, dBTicks, angleTicks)

fig = figure;

axResponse = axes('Parent', fig);
axResponse.Visible = 'off';
hold(axResponse, 'on')
axis(axResponse, 'equal')
ylim(axResponse,[0 dynRange])
xlim(axResponse, [-dynRange dynRange])


%Set background color to white (inside half circle)
patch('XData', cos(0:pi/50:2*pi) * dynRange, ...
    'YData', sin(0:pi/50:2*pi) * dynRange,...
    'FaceColor', [1 1 1]);

%Plot angle spokes
for tick = angleTicks
    line(dynRange * [-sin(tick*pi/180) sin(tick*pi/180)], ...
        dynRange * [-cos(tick*pi/180) cos(tick*pi/180)], ...
    'LineStyle', '-', ...
    'Color', [1 1 1]*0.8, ...
    'LineWidth', 0.5);

    text((dynRange*1.08) * sin(tick*pi/180), ...
        (dynRange*1.08) * cos(tick*pi/180), ...
        [int2str(tick) '^\circ'],...
        'HorizontalAlignment', 'center', ...
        'fontSize', 10);
end

    
%Plot dB ticks
txtAngle = 10;
for tick = dBTicks
    line(cos(0:pi/50:2*pi)*(dynRange+tick), sin(0:pi/50:2*pi)*(dynRange+tick), ...
        'LineStyle', '-', ...
        'Color', [1 1 1]*0.8, ...
        'LineWidth', 0.5);
    
    text((dynRange+tick)*cos(txtAngle*pi/180), ...
        (dynRange+tick)*sin(txtAngle*pi/180), ...
        ['  ' num2str(tick)], ...
        'fontsize',8);
end
line(cos(0:pi/50:2*pi)*dynRange, sin(0:pi/50:2*pi)*dynRange, ...
    'LineStyle', '-', ...
    'Color', [0 0 0], ...
    'LineWidth', 1);
line([-dynRange dynRange], [0 0], ...
    'LineStyle', '-', ...
    'Color', [0 0 0], ...
    'LineWidth', 1);


xx = (beamPattern+dynRange) .* sin(thetaScanningAngles*pi/180);
yy = (beamPattern+dynRange) .* cos(thetaScanningAngles*pi/180);
    
plot(axResponse, xx, yy);